# Generated by Django 3.1.1 on 2020-09-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOGS', '0004_auto_20200918_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
